table SampleSuperstore
	lineageTag: 46aaec6e-e6ca-47b9-9e69-b174a043d97e

	column 'Ship Mode'
		dataType: string
		lineageTag: 5f39349c-1ce8-4d8b-a580-5977da51cde7
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 9ca99763-9935-4551-9f67-da34291a447f
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: a2669d63-cb5b-40b6-8919-dfe11b0706da
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 4876c92f-e662-41e3-9eee-c770aebaea28
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 9e9cf436-a949-4e65-b0b5-0829c058cdc4
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 6cb9d362-e0b5-4081-9375-6d1175cc0c32
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 7cd6aaed-4b82-430e-85ad-0fbc94bbfe32
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 9bfa970d-d80c-41f5-88d1-9a596a65e31a
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 4f4d010e-73a4-48af-81fe-c42d9f06c586
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: a172a74a-20fc-46e6-8be9-9649cccac6ba
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: f12a9dec-ba9a-420b-8410-20aad84a9c08
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 2df426b2-e1ec-477c-9f54-7552624cb717
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 6b94fc9d-5849-422a-9e4e-4547065c035e
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition SampleSuperstore = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Kaushik Dubey\Downloads\SampleSuperstore.xlsx"), null, true),
				    SampleSuperstore_Sheet = Source{[Item="SampleSuperstore",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(SampleSuperstore_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Ship Mode", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

